### ISSUE TITLE
lavalink v4 supported 👍 

### ISSUE THREAD

**Issue by phamleduy04** [Tomato6966/erela.js#28]
Lavalink just released v4 (still in beta) for lavalink. Do you plan to update erela.js to support to v4?

https://github.com/lavalink-devs/Lavalink/releases/tag/4.0.0-beta.1

**Comment by Tomato6966** [comment]
It should already support v4, just add node#version = "v4" and node#useVersionPath = true

**Comment by Tomato6966** [comment]
Nope it doesn'T support it, nvm it changed i will change it now

**Comment by CustomTag** [comment]
Looks like the new update wont work
![image](https://github.com/Tomato6966/erela.js/assets/65868765/83f3f63f-fda7-40f5-8134-5bd682cc645a)

**Comment by zoli456** [comment]
Did you fix when you mute/deafen the bot it switch back to websocket?

**Comment by Tomato6966** [comment]
I just fixed it, the issue was related for link queries.

Now it all works for:
Lavalink v2
Lavalink v3 rest/websocket
Lavalink v4

If any more v4 issues (not lavalink related) are coming, please post it in here!

If you setup your nodes like that:
```js
 nodes: [{
        // other information like, identifier, host, password, port, regions, retryDelay, retryAmount
        version: "v4",
        useVersionPath: true,
    }]
```
you can use the newest v4 lavalink version!
Supporting the artwork urls ->> but also renaming it to thumbnail, so you don't have to do stuff!

**Comment by Tomato6966** [comment]
> Did you fix when you mute/deafen the bot it switch back to websocket?

This bug never occurred to me...

**Comment by zoli456** [comment]
> > Did you fix when you mute/deafen the bot it switch back to websocket?
> 
> This bug never occurred to me...

I used this https://github.com/SudhanPlayz/Discord-MusicBot/tree/v5 as the base for my bot and replaced erela.sj with your version but when i try to mute the bot it cause a short pause in the music and a warning pop up in the console about the removal of the websocket communication.

**Comment by N1C0exe** [comment]
> 

Yea also mine reconnect to websocket when mute/deafen

**Comment by CustomTag** [comment]
> > 
> 
> Yea also mine reconnect to websocket when mute/deafen

Yeah this also happens to me
![image](https://github.com/Tomato6966/erela.js/assets/65868765/0e2e838a-1e4b-4839-8d02-1810d3f91347)
everytime I pause the music its using the websocket and not the rest one so idk if its a bug or something

**Comment by Tomato6966** [comment]
Oh you mean in lavalink info logs, i thought you ment the erela.js error message(s)

**Comment by Tomato6966** [comment]
> 

https://github.com/Tomato6966/erela.js/commit/3784f91450a1637f5fbee40889ee84d4f2350d6c Theoredically fixed with that commit-push. However I'm unsure if it doesn't affect v2-v3

it was a method-call from the original erela.js which i was unsure why it was there, so i just let it be. i removed it now, and i think that was causing the warning methods...

**Comment by Tomato6966** [comment]
If any other v4 issues are present, please hit me up!

**Comment by zoli456** [comment]
The websocket switch still happens on v3 after the update. I will test v4 later.

**Comment by CustomTag** [comment]
I guess that the new Slim branches is broken as its giving me this error
![image](https://github.com/Tomato6966/erela.js/assets/65868765/574cb994-0439-4b79-8573-25dea224d570)

**Comment by CustomTag** [comment]
And this is also a issue I guess with the new Silm branches
![image](https://github.com/Tomato6966/erela.js/assets/65868765/25ad4a6f-9ebe-4aaa-8fb3-698d5461a3ff)

**Comment by Tomato6966** [comment]
Slim branch isnt tested yet..
I will take a look soon tho (getting operated today)

**Comment by CustomTag** [comment]
> Slim branch isnt tested yet.. I will take a look soon tho (getting operated today)

Okay thanks for letting me know

**Comment by vuthanhtrung2010** [comment]
> If any other v4 issues are present, please hit me up!

Is the multipurpose bot sharded with cluster if I modify it to this package, it still cant connect to v4, package.json added "erela.js": "Tomato6966/erela.js"
Also here is my erela event creation:
```

var {
    Manager
  } = require("erela.js"),
  
    Spotify = require("erela.js-spotify"),
    Deezer = require("erela.js-deezer"),
    Facebook = require("erela.js-facebook"),
    config = require(`${process.cwd()}/botconfig/config.json`),
    clientID = process.env.clientID || config.spotify.clientID,
    clientSecret = process.env.clientSecret || config.spotify.clientSecret;
  module.exports = (client) => {
      if (!clientID || !clientSecret || clientID.length < 5 || clientSecret.length < 5) {
        const ManagerOptions = {
          plugins: [
            new Deezer(),
            new Facebook(),
          ],
          send(id, payload) {
            var guild = client.guilds.cache.get(id);
            if (guild) guild.shard.send(payload);
          }
        };
        client.manager = new Manager({
          ...ManagerOptions,
          nodes: collect(config.clientsettings.nodes)
        });
      } else {
        client.manager = new Manager({
          nodes: collect(config.clientsettings.nodes),
          plugins: [
            new Spotify({
              clientID, //get a clientid from there: https://developer.spotify.com/dashboard
              clientSecret
            }),
            new Deezer(),
            new Facebook(),
          ],
          send(id, payload) {
            var guild = client.guilds.cache.get(id);
            if (guild) guild.shard.send(payload);
          },
        });
      }
      //require the other events
      require("./node_events")(client)
      require("./client_events")(client)
      require("./events")(client)
      require("./musicsystem")(client)
      
  };

  function collect(node) {
    return node.map(x => {
        
      if (!x.host) throw new RangeError('"host" must be provided');
      if (!x.password) throw new RangeError('"password" must be provided');
      if (typeof x.port !== 'number') throw new RangeError('"port" must be a number');
      if (x.retryAmount && typeof x.retryAmount !== 'number') throw new RangeError('Retry amount must be a number');
      if (x.retryDelay && typeof x.retryDelay !== 'number') throw new RangeError('Retry delay must be a number');
      if (x.secure && typeof x.secure !== 'boolean') throw new RangeError('Secure must be a boolean');
      if (x.useVersionPath && typeof x.useVersionPath !== 'boolean') throw new RangeError('useVersionPath must be a boolean');

      return {
          host: x.host,
          password: x.password ? x.password : 'youshallnotpass',
          port: x.port && !isNaN(x.port) ? Number(x.port) : 2333,
          identifier: x.identifier || x.host,
          retryAmount: x.retryAmount ? Number(x.retryAmount) : 5,
          retryDelay: x.retryDelay ? Number(x.retryDelay) : 5000,
          secure: x.secure ? x.secure : false
      };
    });
}
```

I modified this code and this is my config for a v4:
{
                "identifier": "3",
                "host": "lava.alfari.id",
                "port": 443,
                "password": "youshallnotpass",
                "version": "v4",
                "useVersionPath": true,
                "secure": true
            }
and obv it returned 404, or 401, most are 404.
